spring:
 application:
   name: CONFIG-DEFAULT
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true
  service-url :
   defaultZone: http://localhost:8761/eureka
